// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rent.Data;

namespace Rent.Migrations
{
    [DbContext(typeof(RentContext))]
    partial class RentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rent.Models.Area", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CleaningPlanID");

                    b.Property<string>("Description");

                    b.Property<int?>("TranslationID");

                    b.HasKey("ID");

                    b.HasIndex("CleaningPlanID");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("Rent.Models.BlackListedToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BlackListTime");

                    b.Property<string>("IP");

                    b.Property<int>("LoginID");

                    b.Property<string>("TokenGuid");

                    b.HasKey("ID");

                    b.HasIndex("LoginID");

                    b.ToTable("BlackListedToken");
                });

            modelBuilder.Entity("Rent.Models.CleaningPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("HasFloors");

                    b.Property<int?>("TranslationID");

                    b.HasKey("ID");

                    b.ToTable("CleaningPlan");
                });

            modelBuilder.Entity("Rent.Models.CleaningTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int?>("AreaID");

                    b.Property<string>("Comment");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("FirstCleaned");

                    b.Property<int?>("FloorID");

                    b.Property<string>("Frequency");

                    b.Property<int?>("LastTaskCompletedID");

                    b.Property<int?>("LocationID");

                    b.Property<string>("Place");

                    b.Property<int?>("ProjectID");

                    b.Property<int?>("ProjectItemID");

                    b.Property<int>("SquareMeters");

                    b.Property<byte?>("TimesOfYear");

                    b.Property<int?>("UserResposibleID");

                    b.HasKey("ID");

                    b.HasIndex("AreaID");

                    b.HasIndex("FloorID");

                    b.HasIndex("LastTaskCompletedID");

                    b.HasIndex("LocationID");

                    b.HasIndex("ProjectItemID");

                    b.HasIndex("UserResposibleID");

                    b.ToTable("CleaningTask");
                });

            modelBuilder.Entity("Rent.Models.CleaningTaskCompleted", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CleaningTaskID");

                    b.Property<string>("Comment");

                    b.Property<int>("CompletedByUserID");

                    b.Property<DateTime>("CompletedDate");

                    b.Property<bool>("Confirmed");

                    b.HasKey("ID");

                    b.HasIndex("CleaningTaskID");

                    b.HasIndex("CompletedByUserID");

                    b.ToTable("CleaningTaskCompleted");
                });

            modelBuilder.Entity("Rent.Models.Conversation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NewestMessageID");

                    b.Property<bool>("Open");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("NewestMessageID")
                        .IsUnique()
                        .HasFilter("[NewestMessageID] IS NOT NULL");

                    b.ToTable("Conversation");
                });

            modelBuilder.Entity("Rent.Models.ConversationUsers", b =>
                {
                    b.Property<int>("ConversationID");

                    b.Property<int>("UserID");

                    b.Property<int?>("LastSeenMessageID");

                    b.Property<bool>("NotificationsOn");

                    b.Property<int>("UnseenMessages");

                    b.HasKey("ConversationID", "UserID");

                    b.HasIndex("LastSeenMessageID");

                    b.HasIndex("UserID");

                    b.ToTable("ConversationUsers");
                });

            modelBuilder.Entity("Rent.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanReadLogs");

                    b.Property<string>("Comment");

                    b.Property<int?>("ConversationID");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("Disabled");

                    b.Property<int>("GeneralFolderID");

                    b.Property<bool>("HasStandardFolders");

                    b.Property<string>("ImageLocation");

                    b.Property<int?>("KeyAccountManagerID");

                    b.Property<int?>("MainUserID");

                    b.Property<int>("ManagementFolderID");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PasswordsLastUpdated");

                    b.Property<int>("PrivateFolderID");

                    b.Property<int?>("ProjectItemID");

                    b.Property<int?>("SalesRepID");

                    b.Property<int>("Status");

                    b.Property<int?>("UpdatePasswordsAtSecondsInterval");

                    b.HasKey("ID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("GeneralFolderID");

                    b.HasIndex("KeyAccountManagerID");

                    b.HasIndex("MainUserID");

                    b.HasIndex("ManagementFolderID");

                    b.HasIndex("PrivateFolderID");

                    b.HasIndex("ProjectItemID")
                        .IsUnique()
                        .HasFilter("[ProjectItemID] IS NOT NULL");

                    b.HasIndex("SalesRepID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Rent.Models.DocumentFolder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasParentPermissions");

                    b.Property<int?>("ParentDocumentFolderID");

                    b.Property<int?>("ProjectItemID");

                    b.Property<bool>("Removable");

                    b.Property<int?>("RootDocumentFolderID");

                    b.Property<bool>("Standard");

                    b.Property<string>("Title");

                    b.Property<bool>("VisibleToAllRoles");

                    b.HasKey("ID");

                    b.HasIndex("ProjectItemID")
                        .IsUnique()
                        .HasFilter("[ProjectItemID] IS NOT NULL");

                    b.HasIndex("RootDocumentFolderID");

                    b.ToTable("DocumentFolder");
                });

            modelBuilder.Entity("Rent.Models.Floor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("TranslationID");

                    b.HasKey("ID");

                    b.ToTable("Floor");
                });

            modelBuilder.Entity("Rent.Models.FolderPermission", b =>
                {
                    b.Property<int>("FolderID");

                    b.Property<int>("RoleID");

                    b.Property<bool>("Edit");

                    b.Property<bool>("Read");

                    b.HasKey("FolderID", "RoleID");

                    b.ToTable("FolderPermission");
                });

            modelBuilder.Entity("Rent.Models.General.Document", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DocumentFolderID");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.HasIndex("DocumentFolderID");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("Rent.Models.Important.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<int>("Category");

                    b.Property<int?>("LocationId");

                    b.Property<int>("SubjectId");

                    b.Property<DateTime>("Time");

                    b.Property<string>("Title");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Rent.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("CleaningFolderID");

                    b.Property<int>("CleaningplanFolderID");

                    b.Property<string>("Comment");

                    b.Property<int?>("CustomerContactID");

                    b.Property<int?>("CustomerConversationID");

                    b.Property<int?>("CustomerID");

                    b.Property<bool>("Disabled");

                    b.Property<int?>("FanCoilFolderID");

                    b.Property<string>("FirestoreConversationStaff");

                    b.Property<DateTime?>("FirstQualityReportTime");

                    b.Property<int>("GeneralFolderID");

                    b.Property<string>("ImageLocation");

                    b.Property<int>("IntervalOfServiceLeaderMeeting");

                    b.Property<double?>("Lat");

                    b.Property<int?>("LatestQualityReportID");

                    b.Property<int>("LocationEconomyID");

                    b.Property<int>("LocationHourID");

                    b.Property<double?>("Lon");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfQualityReportsSinceUpdate");

                    b.Property<int?>("PeriodicFolderID");

                    b.Property<string>("Phone");

                    b.Property<int?>("ProjectItemID");

                    b.Property<int?>("ProjectNumber");

                    b.Property<int?>("ServiceLeaderID");

                    b.Property<int?>("TeamConversationID");

                    b.Property<int?>("WindowFolderID");

                    b.HasKey("ID");

                    b.HasIndex("CleaningFolderID");

                    b.HasIndex("CleaningplanFolderID");

                    b.HasIndex("CustomerContactID");

                    b.HasIndex("CustomerConversationID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("FanCoilFolderID");

                    b.HasIndex("GeneralFolderID");

                    b.HasIndex("LatestQualityReportID");

                    b.HasIndex("LocationEconomyID");

                    b.HasIndex("LocationHourID");

                    b.HasIndex("PeriodicFolderID");

                    b.HasIndex("ProjectItemID")
                        .IsUnique()
                        .HasFilter("[ProjectItemID] IS NOT NULL");

                    b.HasIndex("ServiceLeaderID");

                    b.HasIndex("TeamConversationID");

                    b.HasIndex("WindowFolderID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Rent.Models.LocationEconomy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PricePerHourCategory");

                    b.Property<float>("PriceRegularCleaning");

                    b.Property<float>("PriceWindowCleaning");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("ID");

                    b.ToTable("LocationEconomy");
                });

            modelBuilder.Entity("Rent.Models.LocationHour", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ChristAscension");

                    b.Property<bool>("ChristmasDay");

                    b.Property<bool>("ChristmasEve");

                    b.Property<bool>("DifferentWeeks");

                    b.Property<bool>("EasterDay");

                    b.Property<bool>("GoodFriday");

                    b.Property<float>("L_Fri");

                    b.Property<float>("L_Mon");

                    b.Property<float>("L_Sat");

                    b.Property<float>("L_Sun");

                    b.Property<float>("L_Thu");

                    b.Property<float>("L_Tue");

                    b.Property<float>("L_Wed");

                    b.Property<bool>("MaundyThursday");

                    b.Property<bool>("NewyearsDay");

                    b.Property<bool>("NewyearsEve");

                    b.Property<bool>("Palmsunday");

                    b.Property<bool>("PrayerDay");

                    b.Property<bool>("SecondEasterDay");

                    b.Property<bool>("SndChristmasDay");

                    b.Property<bool>("SndPentecost");

                    b.Property<float>("U_Fri");

                    b.Property<float>("U_Mon");

                    b.Property<float>("U_Sat");

                    b.Property<float>("U_Sun");

                    b.Property<float>("U_Thu");

                    b.Property<float>("U_Tue");

                    b.Property<float>("U_Wed");

                    b.Property<bool>("WhitSunday");

                    b.HasKey("ID");

                    b.ToTable("LocationHour");
                });

            modelBuilder.Entity("Rent.Models.LocationLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CustomerCreated");

                    b.Property<DateTime>("DateCreated");

                    b.Property<int?>("LocationID");

                    b.Property<string>("Log");

                    b.Property<int?>("ProjectItemID");

                    b.Property<string>("Title");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("ProjectItemID");

                    b.HasIndex("UserID");

                    b.ToTable("LocationLog");
                });

            modelBuilder.Entity("Rent.Models.LocationUser", b =>
                {
                    b.Property<int>("LocationID");

                    b.Property<int>("UserID");

                    b.Property<string>("HourText");

                    b.Property<string>("Title");

                    b.HasKey("LocationID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("LocationUser");
                });

            modelBuilder.Entity("Rent.Models.Login", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<DateTime>("PasswordLastUpdated");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Rent.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConversationID");

                    b.Property<string>("MessageText");

                    b.Property<DateTime>("SentTime");

                    b.Property<int?>("SpecialMessageID");

                    b.Property<string>("Type");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("SpecialMessageID");

                    b.HasIndex("UserID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Rent.Models.MoreWork", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActualCompletedTime");

                    b.Property<int>("CleaningPlanID");

                    b.Property<int>("CreatedByUserID");

                    b.Property<string>("Description");

                    b.Property<DateTime>("ExpectedCompletedTime");

                    b.Property<float?>("Hours");

                    b.Property<int>("LocationID");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.ToTable("MoreWork");
                });

            modelBuilder.Entity("Rent.Models.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<bool>("OnlyMasterCanChange");

                    b.HasKey("ID");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Rent.Models.PermissionsTemplate", b =>
                {
                    b.Property<int>("PermissionID");

                    b.Property<int>("RoleID");

                    b.Property<bool>("Create");

                    b.Property<bool>("Delete");

                    b.Property<bool>("Read");

                    b.Property<bool>("Update");

                    b.HasKey("PermissionID", "RoleID");

                    b.ToTable("PermissionsTemplate");
                });

            modelBuilder.Entity("Rent.Models.Projects.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressName");

                    b.Property<double?>("Lat");

                    b.Property<double?>("Lon");

                    b.Property<int>("ProjectItemID");

                    b.HasKey("ID");

                    b.HasIndex("ProjectItemID")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Rent.Models.Projects.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<int>("ProjectItemID");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("ProjectItemID")
                        .IsUnique();

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Rent.Models.Projects.FirestoreConversation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConversationID");

                    b.Property<int>("ProjectItemID");

                    b.HasKey("ID");

                    b.HasIndex("ProjectItemID")
                        .IsUnique();

                    b.ToTable("FirestoreConversation");
                });

            modelBuilder.Entity("Rent.Models.Projects.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("ParentID");

                    b.Property<string>("Path");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProjectID");

                    b.Property<int>("ProjectItemType");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectItem");
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectItemAccess", b =>
                {
                    b.Property<int>("ProjectItemID");

                    b.Property<int>("ProjectRoleID");

                    b.Property<bool>("Read");

                    b.Property<bool>("Write");

                    b.HasKey("ProjectItemID", "ProjectRoleID");

                    b.HasIndex("ProjectRoleID");

                    b.ToTable("ProjectItemAccess");
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectItemAccessTemplate", b =>
                {
                    b.Property<int>("ProjectItemType");

                    b.Property<int>("ProjectRoleID");

                    b.Property<bool>("Read");

                    b.Property<bool>("Write");

                    b.HasKey("ProjectItemType", "ProjectRoleID");

                    b.HasIndex("ProjectRoleID");

                    b.ToTable("ProjectItemAccessTemplate");
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectItemUser", b =>
                {
                    b.Property<int>("ProjectItemID");

                    b.Property<int>("UserID");

                    b.Property<bool>("Read");

                    b.Property<bool>("Write");

                    b.HasKey("ProjectItemID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("ProjectItemUser");
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectUser", b =>
                {
                    b.Property<int>("ProjectID");

                    b.Property<int>("UserID");

                    b.HasKey("ProjectID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("Rent.Models.QualityReport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<DateTime?>("CompletedTime");

                    b.Property<int?>("LocationID");

                    b.Property<DateTime?>("NextReport");

                    b.Property<int?>("ProjectItemID");

                    b.Property<int?>("RatingID");

                    b.Property<DateTime>("Time");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("ProjectItemID");

                    b.HasIndex("RatingID");

                    b.HasIndex("UserID");

                    b.ToTable("QualityReport");
                });

            modelBuilder.Entity("Rent.Models.QualityReportItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CleaningTaskID");

                    b.Property<string>("Comment");

                    b.Property<string>("ImageLocation");

                    b.Property<int>("QualityReportID");

                    b.Property<byte>("Rating");

                    b.HasKey("ID");

                    b.HasIndex("CleaningTaskID");

                    b.HasIndex("QualityReportID");

                    b.ToTable("QualityReportItem");
                });

            modelBuilder.Entity("Rent.Models.Rating", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("Rent.Models.RatingItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int>("RatedByID");

                    b.Property<int>("RatingID");

                    b.Property<DateTime>("TimeRated");

                    b.Property<string>("Title");

                    b.Property<int>("Value");

                    b.HasKey("ID");

                    b.HasIndex("RatedByID");

                    b.HasIndex("RatingID");

                    b.ToTable("RatingItem");
                });

            modelBuilder.Entity("Rent.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Rank");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Rent.Models.SpecialMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("SpecialMessage");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SpecialMessage");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Absence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AbsenceReasonID");

                    b.Property<string>("Comment");

                    b.Property<int>("CreatorID");

                    b.Property<DateTime>("From");

                    b.Property<bool>("IsRequest");

                    b.Property<int>("RequestID");

                    b.Property<DateTime>("To");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("AbsenceReasonID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("RequestID");

                    b.HasIndex("UserID");

                    b.ToTable("Absence");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.AbsenceReason", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanManagerCreate");

                    b.Property<bool>("CanManagerRequest");

                    b.Property<bool>("CanUserCreate");

                    b.Property<bool>("CanUserRequest");

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("AbsenceReason");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.AccidentReport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AbsenceDurationDays");

                    b.Property<int>("AccidentReportType");

                    b.Property<string>("ActionTaken");

                    b.Property<int?>("CreatorID");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description");

                    b.Property<string>("Place");

                    b.Property<int>("RequestID");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("RequestID");

                    b.HasIndex("UserID");

                    b.ToTable("AccidentReports");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Agreement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Agreement");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProjectItemID");

                    b.HasKey("ID");

                    b.HasIndex("ProjectItemID")
                        .IsUnique()
                        .HasFilter("[ProjectItemID] IS NOT NULL");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Contract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgreementID");

                    b.Property<DateTime>("From");

                    b.Property<DateTime>("To");

                    b.Property<int>("UserID");

                    b.Property<float>("WeeklyHours");

                    b.HasKey("ID");

                    b.HasIndex("AgreementID");

                    b.HasIndex("UserID");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Holiday", b =>
                {
                    b.Property<string>("Name");

                    b.Property<string>("CountryCode");

                    b.HasKey("Name", "CountryCode");

                    b.ToTable("Holiday");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Noti", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<string>("NotiType");

                    b.Property<int>("ReceiverID");

                    b.Property<bool>("Seen");

                    b.Property<DateTime>("SendTime");

                    b.Property<int?>("SenderID");

                    b.Property<int>("SubjectID");

                    b.Property<string>("Title");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("Notis");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<int?>("ProjectItemID");

                    b.Property<DateTime>("SendTime");

                    b.Property<string>("Title");

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("ProjectItemID")
                        .IsUnique()
                        .HasFilter("[ProjectItemID] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.ProjectRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasAllPermissions");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("ProjectRole");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Request", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApprovalState");

                    b.Property<int?>("CreatorID");

                    b.Property<DateTime?>("RespondDateTime");

                    b.Property<int?>("ResponderID");

                    b.Property<int?>("SubjectID");

                    b.HasKey("ID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("ResponderID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Work", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("BreakMins");

                    b.Property<int?>("ContractID");

                    b.Property<DateTime>("Date");

                    b.Property<short>("EndTimeMins");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("Modifications");

                    b.Property<string>("Note");

                    b.Property<int?>("ProjectItemID");

                    b.Property<short>("StartTimeMins");

                    b.Property<int?>("WorkContractID");

                    b.HasKey("ID");

                    b.HasIndex("ContractID");

                    b.HasIndex("ProjectItemID");

                    b.ToTable("Work");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkContract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContractID");

                    b.Property<DateTime>("FromDate");

                    b.Property<bool>("IsVisible");

                    b.Property<string>("Note");

                    b.Property<int?>("ProjectItemID");

                    b.Property<DateTime>("ToDate");

                    b.HasKey("ID");

                    b.HasIndex("ContractID");

                    b.HasIndex("ProjectItemID");

                    b.ToTable("WorkContract");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkDay", b =>
                {
                    b.Property<int>("WorkContractID");

                    b.Property<int>("DayOfWeek");

                    b.Property<byte>("IsEvenWeek");

                    b.Property<short>("BreakMins");

                    b.Property<short>("EndTimeMins");

                    b.Property<short>("StartTimeMins");

                    b.HasKey("WorkContractID", "DayOfWeek", "IsEvenWeek");

                    b.ToTable("WorkDay");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkHoliday", b =>
                {
                    b.Property<string>("HolidayName");

                    b.Property<string>("HolidayCountryCode");

                    b.Property<int>("WorkContractID");

                    b.HasKey("HolidayName", "HolidayCountryCode", "WorkContractID");

                    b.HasIndex("WorkContractID");

                    b.ToTable("WorkHoliday");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkInvitation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContractID");

                    b.Property<int>("WorkID");

                    b.HasKey("ID");

                    b.HasIndex("ContractID");

                    b.HasIndex("WorkID");

                    b.ToTable("WorkInvitation");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkRegistration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short?>("BreakMins");

                    b.Property<DateTime>("Date");

                    b.Property<short?>("EndTimeMins");

                    b.Property<int?>("RequestID");

                    b.Property<short?>("StartTimeMins");

                    b.Property<int>("UserID");

                    b.Property<int>("WorkID");

                    b.HasKey("ID");

                    b.HasIndex("RequestID");

                    b.HasIndex("UserID");

                    b.HasIndex("WorkID")
                        .IsUnique();

                    b.ToTable("WorkRegistration");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkReplacement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AbsenceID");

                    b.Property<int?>("ContractID");

                    b.Property<int>("WorkID");

                    b.HasKey("ID");

                    b.HasIndex("AbsenceID");

                    b.HasIndex("ContractID");

                    b.HasIndex("WorkID")
                        .IsUnique();

                    b.ToTable("WorkReplacement");
                });

            modelBuilder.Entity("Rent.Models.Translation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Translation");
                });

            modelBuilder.Entity("Rent.Models.TranslationEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Language");

                    b.Property<string>("Text");

                    b.Property<int>("TranslationID");

                    b.HasKey("ID");

                    b.ToTable("TranslationEntry");
                });

            modelBuilder.Entity("Rent.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientID");

                    b.Property<string>("Comment");

                    b.Property<int?>("CustomerID");

                    b.Property<bool>("Disabled");

                    b.Property<string>("Email");

                    b.Property<int?>("EmployeeNumber");

                    b.Property<string>("FirstName");

                    b.Property<string>("ImageLocation");

                    b.Property<string>("LanguageCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasDefaultValue("en");

                    b.Property<string>("LastName");

                    b.Property<int>("LoginID");

                    b.Property<string>("Phone");

                    b.Property<int?>("ProjectRoleID");

                    b.Property<int?>("RoleID");

                    b.Property<string>("Title");

                    b.Property<string>("UserRole");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("LoginID");

                    b.HasIndex("ProjectRoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Rent.Models.UserPermissions", b =>
                {
                    b.Property<int>("PermissionID");

                    b.Property<int>("UserID");

                    b.Property<bool>("Create");

                    b.Property<bool>("Delete");

                    b.Property<bool>("Read");

                    b.Property<bool>("Update");

                    b.HasKey("PermissionID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Rent.Models.MessageComplaint", b =>
                {
                    b.HasBaseType("Rent.Models.SpecialMessage");

                    b.Property<string>("ImageLocator");

                    b.Property<int>("Status");

                    b.Property<DateTime>("Time");

                    b.ToTable("Complaint");

                    b.HasDiscriminator().HasValue("MessageComplaint");
                });

            modelBuilder.Entity("Rent.Models.MessageImage", b =>
                {
                    b.HasBaseType("Rent.Models.SpecialMessage");

                    b.Property<string>("ImageLocator")
                        .HasColumnName("MessageImage_ImageLocator");

                    b.ToTable("Image");

                    b.HasDiscriminator().HasValue("MessageImage");
                });

            modelBuilder.Entity("Rent.Models.MessageMeeting", b =>
                {
                    b.HasBaseType("Rent.Models.SpecialMessage");

                    b.Property<int>("Status")
                        .HasColumnName("MessageMeeting_Status");

                    b.Property<DateTime>("Time")
                        .HasColumnName("MessageMeeting_Time");

                    b.ToTable("Meeting");

                    b.HasDiscriminator().HasValue("MessageMeeting");
                });

            modelBuilder.Entity("Rent.Models.MessageMoreWork", b =>
                {
                    b.HasBaseType("Rent.Models.SpecialMessage");

                    b.Property<int>("Status")
                        .HasColumnName("MessageMoreWork_Status");

                    b.Property<DateTime>("Time")
                        .HasColumnName("MessageMoreWork_Time");

                    b.ToTable("MoreWork");

                    b.HasDiscriminator().HasValue("MessageMoreWork");
                });

            modelBuilder.Entity("Rent.Models.MessageVideo", b =>
                {
                    b.HasBaseType("Rent.Models.SpecialMessage");

                    b.Property<string>("ThumbnailLocator");

                    b.Property<string>("VideoLocator");

                    b.ToTable("Video");

                    b.HasDiscriminator().HasValue("MessageVideo");
                });

            modelBuilder.Entity("Rent.Models.Area", b =>
                {
                    b.HasOne("Rent.Models.CleaningPlan", "CleaningPlan")
                        .WithMany()
                        .HasForeignKey("CleaningPlanID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.BlackListedToken", b =>
                {
                    b.HasOne("Rent.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.CleaningTask", b =>
                {
                    b.HasOne("Rent.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaID");

                    b.HasOne("Rent.Models.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorID");

                    b.HasOne("Rent.Models.CleaningTaskCompleted", "LastTaskCompleted")
                        .WithMany()
                        .HasForeignKey("LastTaskCompletedID");

                    b.HasOne("Rent.Models.Location", "Location")
                        .WithMany("CleaningTasks")
                        .HasForeignKey("LocationID");

                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectItemID");

                    b.HasOne("Rent.Models.User", "UserResposible")
                        .WithMany()
                        .HasForeignKey("UserResposibleID");
                });

            modelBuilder.Entity("Rent.Models.CleaningTaskCompleted", b =>
                {
                    b.HasOne("Rent.Models.CleaningTask", "CleaningTask")
                        .WithMany("CompletedTasks")
                        .HasForeignKey("CleaningTaskID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Conversation", b =>
                {
                    b.HasOne("Rent.Models.Message", "NewestMessage")
                        .WithOne("Conversation")
                        .HasForeignKey("Rent.Models.Conversation", "NewestMessageID");
                });

            modelBuilder.Entity("Rent.Models.ConversationUsers", b =>
                {
                    b.HasOne("Rent.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.Message", "LastSeenMessage")
                        .WithMany()
                        .HasForeignKey("LastSeenMessageID");

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Customer", b =>
                {
                    b.HasOne("Rent.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationID");

                    b.HasOne("Rent.Models.DocumentFolder", "GeneralFolder")
                        .WithMany()
                        .HasForeignKey("GeneralFolderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "KeyAccountManager")
                        .WithMany()
                        .HasForeignKey("KeyAccountManagerID");

                    b.HasOne("Rent.Models.User", "MainUser")
                        .WithMany()
                        .HasForeignKey("MainUserID");

                    b.HasOne("Rent.Models.DocumentFolder", "ManagementFolder")
                        .WithMany()
                        .HasForeignKey("ManagementFolderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.DocumentFolder", "PrivateFolder")
                        .WithMany()
                        .HasForeignKey("PrivateFolderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithOne("Customer")
                        .HasForeignKey("Rent.Models.Customer", "ProjectItemID");

                    b.HasOne("Rent.Models.User", "SalesRep")
                        .WithMany()
                        .HasForeignKey("SalesRepID");
                });

            modelBuilder.Entity("Rent.Models.DocumentFolder", b =>
                {
                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithOne("DocumentFolder")
                        .HasForeignKey("Rent.Models.DocumentFolder", "ProjectItemID");

                    b.HasOne("Rent.Models.DocumentFolder", "RootDocumentFolder")
                        .WithMany("DecendantDocumentFolders")
                        .HasForeignKey("RootDocumentFolderID");
                });

            modelBuilder.Entity("Rent.Models.FolderPermission", b =>
                {
                    b.HasOne("Rent.Models.DocumentFolder", "Folder")
                        .WithMany("FolderPermissions")
                        .HasForeignKey("FolderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.General.Document", b =>
                {
                    b.HasOne("Rent.Models.DocumentFolder", "DocumentFolder")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentFolderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Important.News", b =>
                {
                    b.HasOne("Rent.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Location", b =>
                {
                    b.HasOne("Rent.Models.DocumentFolder", "CleaningFolder")
                        .WithMany()
                        .HasForeignKey("CleaningFolderID");

                    b.HasOne("Rent.Models.DocumentFolder", "CleaningplanFolder")
                        .WithMany()
                        .HasForeignKey("CleaningplanFolderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "CustomerContact")
                        .WithMany()
                        .HasForeignKey("CustomerContactID");

                    b.HasOne("Rent.Models.Conversation", "CustomerConversation")
                        .WithMany()
                        .HasForeignKey("CustomerConversationID");

                    b.HasOne("Rent.Models.Customer", "Customer")
                        .WithMany("Locations")
                        .HasForeignKey("CustomerID");

                    b.HasOne("Rent.Models.DocumentFolder", "FanCoilFolder")
                        .WithMany()
                        .HasForeignKey("FanCoilFolderID");

                    b.HasOne("Rent.Models.DocumentFolder", "GeneralFolder")
                        .WithMany()
                        .HasForeignKey("GeneralFolderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.QualityReport", "LatestQualityReport")
                        .WithMany()
                        .HasForeignKey("LatestQualityReportID");

                    b.HasOne("Rent.Models.LocationEconomy", "LocationEconomy")
                        .WithMany()
                        .HasForeignKey("LocationEconomyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.LocationHour", "LocationHour")
                        .WithMany()
                        .HasForeignKey("LocationHourID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.DocumentFolder", "PeriodicFolder")
                        .WithMany()
                        .HasForeignKey("PeriodicFolderID");

                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithOne("Location")
                        .HasForeignKey("Rent.Models.Location", "ProjectItemID");

                    b.HasOne("Rent.Models.User", "ServiceLeader")
                        .WithMany()
                        .HasForeignKey("ServiceLeaderID");

                    b.HasOne("Rent.Models.Conversation", "TeamConversation")
                        .WithMany()
                        .HasForeignKey("TeamConversationID");

                    b.HasOne("Rent.Models.DocumentFolder", "WindowFolder")
                        .WithMany()
                        .HasForeignKey("WindowFolderID");
                });

            modelBuilder.Entity("Rent.Models.LocationLog", b =>
                {
                    b.HasOne("Rent.Models.Location", "Location")
                        .WithMany("LocationLogs")
                        .HasForeignKey("LocationID");

                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithMany("Logs")
                        .HasForeignKey("ProjectItemID");

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.LocationUser", b =>
                {
                    b.HasOne("Rent.Models.Location", "Location")
                        .WithMany("LocationUsers")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany("LocationUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Message", b =>
                {
                    b.HasOne("Rent.Models.SpecialMessage", "SpecialMessage")
                        .WithMany()
                        .HasForeignKey("SpecialMessageID");

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.MoreWork", b =>
                {
                    b.HasOne("Rent.Models.Location", "Location")
                        .WithMany("MoreWork")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.PermissionsTemplate", b =>
                {
                    b.HasOne("Rent.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Projects.Address", b =>
                {
                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithOne("Address")
                        .HasForeignKey("Rent.Models.Projects.Address", "ProjectItemID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Projects.Comment", b =>
                {
                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithOne("Comment")
                        .HasForeignKey("Rent.Models.Projects.Comment", "ProjectItemID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Projects.FirestoreConversation", b =>
                {
                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithOne("FirestoreConversations")
                        .HasForeignKey("Rent.Models.Projects.FirestoreConversation", "ProjectItemID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Projects.Project", b =>
                {
                    b.HasOne("Rent.Models.Projects.Project", "Parent")
                        .WithMany("Projects")
                        .HasForeignKey("ParentID");
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectItem", b =>
                {
                    b.HasOne("Rent.Models.Projects.Project", "Project")
                        .WithMany("ProjectItems")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectItemAccess", b =>
                {
                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithMany("ProjectItemAccesses")
                        .HasForeignKey("ProjectItemID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.TimePlanning.ProjectRole", "ProjectRole")
                        .WithMany()
                        .HasForeignKey("ProjectRoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectItemAccessTemplate", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.ProjectRole", "ProjectRole")
                        .WithMany()
                        .HasForeignKey("ProjectRoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectItemUser", b =>
                {
                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithMany("ProjectItemUsers")
                        .HasForeignKey("ProjectItemID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany("ProjectItemUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.Projects.ProjectUser", b =>
                {
                    b.HasOne("Rent.Models.Projects.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.QualityReport", b =>
                {
                    b.HasOne("Rent.Models.Location", "Location")
                        .WithMany("QualityReports")
                        .HasForeignKey("LocationID");

                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithMany("QualityReports")
                        .HasForeignKey("ProjectItemID");

                    b.HasOne("Rent.Models.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingID");

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.QualityReportItem", b =>
                {
                    b.HasOne("Rent.Models.CleaningTask", "CleaningTask")
                        .WithMany()
                        .HasForeignKey("CleaningTaskID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.QualityReport", "QualityReport")
                        .WithMany("QualityReportItems")
                        .HasForeignKey("QualityReportID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.RatingItem", b =>
                {
                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("RatedByID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.Rating", "Rating")
                        .WithMany("RatingItems")
                        .HasForeignKey("RatingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Absence", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.AbsenceReason", "AbsenceReason")
                        .WithMany("Absence")
                        .HasForeignKey("AbsenceReasonID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "Creator")
                        .WithMany("AbsencesCreated")
                        .HasForeignKey("CreatorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rent.Models.TimePlanning.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany("Absences")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.AccidentReport", b =>
                {
                    b.HasOne("Rent.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID");

                    b.HasOne("Rent.Models.TimePlanning.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Client", b =>
                {
                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithOne("Client")
                        .HasForeignKey("Rent.Models.TimePlanning.Client", "ProjectItemID");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Contract", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.Agreement", "Agreement")
                        .WithMany("Contracts")
                        .HasForeignKey("AgreementID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany("Contracts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Noti", b =>
                {
                    b.HasOne("Rent.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Post", b =>
                {
                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithOne("Post")
                        .HasForeignKey("Rent.Models.TimePlanning.Post", "ProjectItemID");

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Request", b =>
                {
                    b.HasOne("Rent.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID");

                    b.HasOne("Rent.Models.User", "Responder")
                        .WithMany()
                        .HasForeignKey("ResponderID");

                    b.HasOne("Rent.Models.User", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.Work", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.Contract", "Contract")
                        .WithMany("Work")
                        .HasForeignKey("ContractID");

                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithMany("Work")
                        .HasForeignKey("ProjectItemID");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkContract", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.Contract", "Contract")
                        .WithMany("WorkContracts")
                        .HasForeignKey("ContractID");

                    b.HasOne("Rent.Models.Projects.ProjectItem", "ProjectItem")
                        .WithMany("WorkContracts")
                        .HasForeignKey("ProjectItemID");
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkDay", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.WorkContract", "WorkContract")
                        .WithMany("WorkDays")
                        .HasForeignKey("WorkContractID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkHoliday", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.WorkContract", "WorkContract")
                        .WithMany("WorkHolidays")
                        .HasForeignKey("WorkContractID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.TimePlanning.Holiday", "Holiday")
                        .WithMany("WorkHolidays")
                        .HasForeignKey("HolidayName", "HolidayCountryCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkInvitation", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.Contract", "Contract")
                        .WithMany("WorkInvitations")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.TimePlanning.Work", "Work")
                        .WithMany("WorkInvitations")
                        .HasForeignKey("WorkID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkRegistration", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestID");

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.TimePlanning.Work", "Work")
                        .WithOne("WorkRegistration")
                        .HasForeignKey("Rent.Models.TimePlanning.WorkRegistration", "WorkID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.TimePlanning.WorkReplacement", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.Absence", "Absence")
                        .WithMany()
                        .HasForeignKey("AbsenceID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.TimePlanning.Contract", "Contract")
                        .WithMany("WorkReplacements")
                        .HasForeignKey("ContractID");

                    b.HasOne("Rent.Models.TimePlanning.Work", "Work")
                        .WithOne("WorkReplacement")
                        .HasForeignKey("Rent.Models.TimePlanning.WorkReplacement", "WorkID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent.Models.User", b =>
                {
                    b.HasOne("Rent.Models.TimePlanning.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID");

                    b.HasOne("Rent.Models.Customer", "Customer")
                        .WithMany("Users")
                        .HasForeignKey("CustomerID");

                    b.HasOne("Rent.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.TimePlanning.ProjectRole", "ProjectRole")
                        .WithMany()
                        .HasForeignKey("ProjectRoleID");

                    b.HasOne("Rent.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");
                });

            modelBuilder.Entity("Rent.Models.UserPermissions", b =>
                {
                    b.HasOne("Rent.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
